"""add section 7 8 9 tables

Revision ID: 00af9d05cb52
Revises: ec9d7805a48d
Create Date: 2026-09-27 16:42:59.881264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00af9d05cb52'
down_revision: Union[str, Sequence[str], None] = 'ec9d7805a48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sds_physical_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sds_document_id', sa.Integer(), nullable=False),
    sa.Column('physical_state', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('odor', sa.Text(), nullable=True),
    sa.Column('ph', sa.Text(), nullable=True),
    sa.Column('flash_point', sa.Text(), nullable=True),
    sa.Column('boiling_point', sa.Text(), nullable=True),
    sa.Column('melting_freezing_point', sa.Text(), nullable=True),
    sa.Column('density', sa.Text(), nullable=True),
    sa.Column('viscosity', sa.Text(), nullable=True),
    sa.Column('solubility', sa.Text(), nullable=True),
    sa.Column('vapour_pressure', sa.Text(), nullable=True),
    sa.Column('flammability', sa.Text(), nullable=True),
    sa.Column('explosive_properties', sa.Text(), nullable=True),
    sa.Column('oxidising_properties', sa.Text(), nullable=True),
    sa.Column('lower_explosion_limit', sa.Text(), nullable=True),
    sa.Column('upper_explosion_limit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sds_document_id'], ['sds_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sds_physical_properties_id'), 'sds_physical_properties', ['id'], unique=False)
    op.create_index(op.f('ix_sds_physical_properties_sds_document_id'), 'sds_physical_properties', ['sds_document_id'], unique=True)
    op.create_table('sds_ppe_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sds_document_id', sa.Integer(), nullable=False),
    sa.Column('respiratory_protection', sa.JSON(), nullable=False),
    sa.Column('hand_protection', sa.JSON(), nullable=False),
    sa.Column('glove_materials', sa.JSON(), nullable=False),
    sa.Column('glove_thickness', sa.JSON(), nullable=False),
    sa.Column('eye_face_protection', sa.JSON(), nullable=False),
    sa.Column('body_protection', sa.JSON(), nullable=False),
    sa.Column('engineering_controls', sa.JSON(), nullable=False),
    sa.Column('exposure_limits', sa.JSON(), nullable=False),
    sa.Column('dnel', sa.JSON(), nullable=False),
    sa.Column('pnec', sa.JSON(), nullable=False),
    sa.Column('hygiene_measures', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sds_document_id'], ['sds_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sds_ppe_info_id'), 'sds_ppe_info', ['id'], unique=False)
    op.create_index(op.f('ix_sds_ppe_info_sds_document_id'), 'sds_ppe_info', ['sds_document_id'], unique=True)
    op.create_table('sds_storage_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sds_document_id', sa.Integer(), nullable=False),
    sa.Column('handling_precautions', sa.JSON(), nullable=False),
    sa.Column('storage_conditions', sa.JSON(), nullable=False),
    sa.Column('incompatible_materials', sa.JSON(), nullable=False),
    sa.Column('fire_explosion_precautions', sa.JSON(), nullable=False),
    sa.Column('specific_end_use', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sds_document_id'], ['sds_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sds_storage_info_id'), 'sds_storage_info', ['id'], unique=False)
    op.create_index(op.f('ix_sds_storage_info_sds_document_id'), 'sds_storage_info', ['sds_document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sds_storage_info_sds_document_id'), table_name='sds_storage_info')
    op.drop_index(op.f('ix_sds_storage_info_id'), table_name='sds_storage_info')
    op.drop_table('sds_storage_info')
    op.drop_index(op.f('ix_sds_ppe_info_sds_document_id'), table_name='sds_ppe_info')
    op.drop_index(op.f('ix_sds_ppe_info_id'), table_name='sds_ppe_info')
    op.drop_table('sds_ppe_info')
    op.drop_index(op.f('ix_sds_physical_properties_sds_document_id'), table_name='sds_physical_properties')
    op.drop_index(op.f('ix_sds_physical_properties_id'), table_name='sds_physical_properties')
    op.drop_table('sds_physical_properties')
    # ### end Alembic commands ###
