"""add preparation date to sds documents

Revision ID: 483dce565ad2
Revises: 01584b27a62e
Create Date: 2026-09-18 15:27:46.026431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483dce565ad2'
down_revision: Union[str, Sequence[str], None] = '01584b27a62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sds_documents', sa.Column('preparation_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sds_documents', 'preparation_date')
    # ### end Alembic commands ###
