"""add hazard precautionary and ghs tables

Revision ID: cc2c54165c3d
Revises: 483dce565ad2
Create Date: 2026-09-22 09:01:49.937619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2c54165c3d'
down_revision: Union[str, Sequence[str], None] = '483dce565ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghs_pictograms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sds_document_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sds_document_id'], ['sds_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sds_document_id', 'code', name='uq_sds_ghs_code')
    )
    op.create_index(op.f('ix_ghs_pictograms_code'), 'ghs_pictograms', ['code'], unique=False)
    op.create_index(op.f('ix_ghs_pictograms_id'), 'ghs_pictograms', ['id'], unique=False)
    op.create_index(op.f('ix_ghs_pictograms_sds_document_id'), 'ghs_pictograms', ['sds_document_id'], unique=False)
    op.create_table('hazard_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sds_document_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sds_document_id'], ['sds_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sds_document_id', 'code', name='uq_sds_hazard_code')
    )
    op.create_index(op.f('ix_hazard_statements_code'), 'hazard_statements', ['code'], unique=False)
    op.create_index(op.f('ix_hazard_statements_id'), 'hazard_statements', ['id'], unique=False)
    op.create_index(op.f('ix_hazard_statements_sds_document_id'), 'hazard_statements', ['sds_document_id'], unique=False)
    op.create_table('precautionary_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sds_document_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sds_document_id'], ['sds_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sds_document_id', 'code', name='uq_sds_precautionary_code')
    )
    op.create_index(op.f('ix_precautionary_statements_code'), 'precautionary_statements', ['code'], unique=False)
    op.create_index(op.f('ix_precautionary_statements_id'), 'precautionary_statements', ['id'], unique=False)
    op.create_index(op.f('ix_precautionary_statements_sds_document_id'), 'precautionary_statements', ['sds_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_precautionary_statements_sds_document_id'), table_name='precautionary_statements')
    op.drop_index(op.f('ix_precautionary_statements_id'), table_name='precautionary_statements')
    op.drop_index(op.f('ix_precautionary_statements_code'), table_name='precautionary_statements')
    op.drop_table('precautionary_statements')
    op.drop_index(op.f('ix_hazard_statements_sds_document_id'), table_name='hazard_statements')
    op.drop_index(op.f('ix_hazard_statements_id'), table_name='hazard_statements')
    op.drop_index(op.f('ix_hazard_statements_code'), table_name='hazard_statements')
    op.drop_table('hazard_statements')
    op.drop_index(op.f('ix_ghs_pictograms_sds_document_id'), table_name='ghs_pictograms')
    op.drop_index(op.f('ix_ghs_pictograms_id'), table_name='ghs_pictograms')
    op.drop_index(op.f('ix_ghs_pictograms_code'), table_name='ghs_pictograms')
    op.drop_table('ghs_pictograms')
    # ### end Alembic commands ###
